# -*- coding: utf-8 -*-
""".env.exampleipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10NPE16ux4mJG-_OLtgjmNtQ5HC-DApDT
"""

# API Keys
SERPAPI_KEY="your_serpapi_key_here"